name: Run Newman API Tests

on:
  push:
    branches:
      - main  # Change this if your branch name is different
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Newman and Reporters
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Tests
        run: |
          newman run "API Testing.postman_collection.json" \
          -r cli,htmlextra --reporter-htmlextra-export "newman-report.html"

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
